# -*- coding: utf-8 -*-
"""Impact productivity and job satisfaction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqxcsDfxp4ft4hvvNK7ywD0tzdCAiQgM
"""

import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1: Load dataset
df = pd.read_csv("/content/remote_worker_productivity_1000.csv")

# Step 2: Drop irrelevant columns if present
df.drop(columns=['worker_id', 'productivity_label'], inplace=True, errors='ignore')

# Step 3: Encode categorical columns
df = pd.get_dummies(df, columns=['location_type', 'industry_sector'], drop_first=True)

# Step 4: Coerce all columns to numeric and drop rows with non-convertible data
df = df.apply(pd.to_numeric, errors='coerce')
df.dropna(inplace=True)

# Step 5: Separate independent and dependent variables
y = df['productivity_score'].astype(float)
X = df.drop(columns='productivity_score').astype(float)

# Step 6: Add constant for intercept
X = sm.add_constant(X)

# Step 7: Run OLS regression
model = sm.OLS(y, X).fit()
print(model.summary())

# Step 8: Plot heatmap (optional)
plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

# Load and preprocess dataset
df = pd.read_csv("/content/remote_worker_productivity_1000.csv")
df.drop(columns=['worker_id', 'productivity_label'], inplace=True, errors='ignore')
df = pd.get_dummies(df, columns=['location_type', 'industry_sector'], drop_first=True)
df = df.apply(pd.to_numeric, errors='coerce')
df.dropna(inplace=True)

# Pairplot of selected variables
selected_cols = ['productivity_score', 'task_completion_rate', 'real_time_feedback_score', 'calendar_scheduled_usage']
sns.pairplot(df[selected_cols])
plt.suptitle("Pairplot of Selected Variables", y=1.02)
plt.show()

# Boxplot of productivity by industry sector
industry_cols = [col for col in df.columns if col.startswith("industry_sector_")]
industry_data = []

for col in industry_cols:
    sector_name = col.split("_")[-1]
    temp = df[df[col] == 1][['productivity_score']].copy()
    temp['industry'] = sector_name
    industry_data.append(temp)

industry_df = pd.concat(industry_data)

plt.figure(figsize=(12, 6))
sns.boxplot(x='industry', y='productivity_score', data=industry_df)
plt.title("Productivity Score by Industry Sector")
plt.show()

# Histogram of Productivity Score
plt.figure(figsize=(10, 6))
sns.histplot(df['productivity_score'], kde=True, bins=20)
plt.title("Distribution of Productivity Score")
plt.xlabel("Productivity Score")
plt.ylabel("Frequency")
plt.show()

# Boxplot for Remote vs Onsite Productivity
# Identify correct encoded column name
remote_col = [col for col in df.columns if 'location_type_' in col]
if remote_col:
    remote_var = remote_col[0]  # e.g., location_type_Remote
    plt.figure(figsize=(10, 6))
    sns.boxplot(x=df[remote_var], y=df['productivity_score'])
    plt.title(f'Productivity Score by Remote Location ({remote_var})')
    plt.xlabel(f'{remote_var} (0 = Other, 1 = Remote)')
    plt.ylabel('Productivity Score')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# Scatter Plot (Working Hours vs Productivity)
plt.figure(figsize=(10, 6))
sns.scatterplot(x='average_daily_work_hours', y='productivity_score', data=df, hue=remote_var if remote_col else None)
plt.title('Working Hours vs Productivity Score')
plt.xlabel('Working Hours')
plt.ylabel('Productivity Score')
plt.grid(True)
plt.tight_layout()
plt.show()